### ISSUE TITLE
Library not found when running extractor.lua

### ISSUE THREAD

**Issue by frankxu2004** [harvardnlp/data2text#10]
When running extractor.lua, the `require 'MarginalNLLCriterion'` failed. It seems like we are missing some packages here?
`/share/apps/torch/bin/luajit: /share/apps/torch/share/lua/5.1/trepl/init.lua:389: module 'MarginalNLLCriterion' not found:No LuaRocks module found for MarginalNLLCriterion`

**Comment by Harold-Lee-PKU** [comment]
Just change " require 'MarginalNLLCriterion' " to " require 'onmt.modules.MarginalNLLCriterion' " and you are good to go. Or you can make a system link to the actual file.

**Comment by frankxu2004** [comment]
Cool, thanks. I just opened a PR for this.
#11

**Comment by swiseman** [comment]
Thanks, @Harold-Lee-PKU, for answering the question, and thanks, @frankxu2004, for the PR; I've merged it in.
