### ISSUE TITLE
Template Generator scripts

### ISSUE THREAD

**Issue by shubhamagarwal92** [harvardnlp/data2text#16]
Thank you for nice work! 

Could you share the scripts related to the template generator mentioned in the Section 5 of  paper [Challenges in Data-to-Document Generation](https://www.aclweb.org/anthology/D17-1239)?

**Comment by swiseman** [comment]
Hi, 

Sorry for the delay. I just pushed [it](https://github.com/harvardnlp/data2text/blob/master/rulebased.py).

**Comment by shubhamagarwal92** [comment]
Thank you for providing the script. I want to know if the last line is same for all the teams..and was it just these three lines produced as a document summary for each record?

**Comment by swiseman** [comment]
The last line was the same for every summary (though the team names that are substituted in differ). In the script, the player_line is repeated 6 times, for the 6 highest scoring players. So each summary should be a total of 8 sentences.

**Comment by shubhamagarwal92** [comment]
Cool. Thanks a lot. This helps :)
