### ISSUE TITLE
Inconsistency in data_utils.py

### ISSUE THREAD

**Issue by Harold-Lee-PKU** [harvardnlp/data2text#6]
In data_utils.py, according to line 134, the tokes are expected to be "not annoying_number_word(...)", so the annoying_number_word() should return True when the toke should be ignored. Yet at line 116, the annoying_number_word() returns True when the toke should not be ignored. I think this bug may affect the generation model as well as the extraction model.

**Comment by swiseman** [comment]
Yes, thanks for pointing this out; looks like this results in numeric words (e.g., "thirty four") largely being ignored, though of course numbers are extracted. And I agree we should get results for including numeric words as well.
